name: Deploy Website to AWS

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.ANONWEB }}

      - name: Deploy Website
        run: |
          scp -o StrictHostKeyChecking=no -r ./* ubuntu@51.20.53.46
          sudo su
          cd ../../www/wwwroot/panel_ssl_site/
